### ISSUE TITLE
`molecule::atom::Atom::charge` doesn't take bonds into account

### ISSUE THREAD

**Issue by thesketh** [rapodaca/molecule.rs#1]
The charge method for atoms doesn't seem to be taking bonds into account properly. Here's a minimal example showing what happens for formaldehyde:

`cargo.toml`
```toml
[package]
name = "testing"
version = "0.1.0"
authors = ["Travis Hesketh <travis@hesketh.scot>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molecule = {git = "https://github.com/rapodaca/molecule.rs"}
```

`src/main.rs`
```rust
use molecule::bond_order;
use molecule::element;
use molecule::spec;
use molecule::default_molecule;
use molecule::molecule::Molecule;

fn main() {
    let C = element::Element::C;
    let O = element::Element::O;

    let double_bond = bond_order::BondOrder::Double;

    //building formaldehyde
    let a1 = spec::Atom{element: C, hydrogens: 2, ion: 0, isotope: None, parity: None };
    let a2 = spec::Atom{element: O, hydrogens: 0, ion: 0, isotope: None, parity: None };
    let atoms = vec![a1, a2];

    let bond = spec::Bond{sid: 0, tid: 1, order: double_bond, parity: None};
    let bonds = vec![bond];

    let mol_spec = spec::Molecule{atoms, bonds};
    let molecule = default_molecule::DefaultMolecule::build(mol_spec).unwrap();
    println!("{}", molecule.charge(&0).unwrap());
    // prints 2
    println!("{}", molecule.charge(&1).unwrap());
    // prints 2
}
```
